# -*- coding: utf-8 -*-
"""sales-etl-sql-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ot9TQSYnN635HQDk2qprSny41wysUIDB
"""

# Sales Data ETL Pipeline (SQL + Python)

## Objective
#Transform raw sales data into a clean, structured dataset and analyze revenue trends using SQL and Python.

## Tools
#- Python (Pandas)
# SQLite (SQL queries)
#- Google Colab

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

products = pd.read_csv("/content/products.csv")
sales_order_header = pd.read_csv("/content/sales_order_header.csv")
sales_order_detail = pd.read_csv("/content/sales_order_detail.csv")

#Load the data

print(products.shape)
print(sales_order_header.shape)
print(sales_order_detail.shape)

products.info()
sales_order_header.info()
sales_order_detail.info()

print(products.isna().sum())
print(sales_order_header.isna().sum())
print(sales_order_detail.isna().sum())

# Type standardization

# Coerce keys/numerics so malformed values become NaN and get caught by checks
products["ProductID"] = pd.to_numeric(products["ProductID"], errors="coerce")

sales_order_header["SalesOrderID"] = pd.to_numeric(sales_order_header["SalesOrderID"], errors="coerce")

sales_order_detail[["SalesOrderID", "SalesOrderDetailID", "ProductID"]] = (
    sales_order_detail[["SalesOrderID", "SalesOrderDetailID", "ProductID"]]
    .apply(pd.to_numeric, errors="coerce")
)

# Money/quantity -> numeric (used in revenue calculations)
for col in ["OrderQty", "UnitPrice", "UnitPriceDiscount"]:
    sales_order_detail[col] = pd.to_numeric(sales_order_detail[col], errors="coerce")

sales_order_header["Freight"] = pd.to_numeric(sales_order_header["Freight"], errors="coerce")

# SalesPersonID is an ID but has many nulls; use nullable Int64 to avoid 279.0 style floats (optional)
sales_order_header["SalesPersonID"] = (
    pd.to_numeric(sales_order_header["SalesPersonID"], errors="coerce")
      .astype("Int64")
)


# Dates -> datetime
# Handles YYYY-MM by assuming day=01 for BOTH OrderDate and ShipDate, assumption that could be questioned

def parse_date_series(s: pd.Series) -> pd.Series:
    s = s.map(lambda x: "" if pd.isna(x) else str(x)).str.strip()
    s = s.where(~s.str.fullmatch(r"\d{4}-\d{2}"), s + "-01")
    return pd.to_datetime(s, format="%Y-%m-%d", errors="coerce")

if sales_order_header["OrderDate"].dtype == "object":
    sales_order_header["OrderDate"] = parse_date_series(sales_order_header["OrderDate"])

if sales_order_header["ShipDate"].dtype == "object":
    sales_order_header["ShipDate"] = parse_date_series(sales_order_header["ShipDate"])


# Minimal sanity checks (interview-friendly)

print("Bad/missing ProductIDs in products:", int(products["ProductID"].isna().sum()))
print("Bad/missing SalesOrderIDs in header:", int(sales_order_header["SalesOrderID"].isna().sum()))
print("Bad/missing SalesOrderDetailIDs in detail:", int(sales_order_detail["SalesOrderDetailID"].isna().sum()))
print("Bad/missing OrderDate:", int(sales_order_header["OrderDate"].isna().sum()))
print("Bad/missing ShipDate:", int(sales_order_header["ShipDate"].isna().sum()))

# Primary Keys
print("Header PK unique:", sales_order_header["SalesOrderID"].is_unique)
print("Detail PK unique:", sales_order_detail["SalesOrderDetailID"].is_unique)
print("Product PK unique:", products["ProductID"].is_unique)

# Foreign Keys
missing_orders = ~sales_order_detail["SalesOrderID"].isin(sales_order_header["SalesOrderID"])
missing_products = ~sales_order_detail["ProductID"].isin(products["ProductID"])

print("Missing Order IDs:", missing_orders.sum())
print("Missing Product IDs:", missing_products.sum())

#resolving duplicates in product master- kept the ones with the most information
# Check duplicates
# If duplicate ProductID rows exist, keep the row with the fewest nulls (transparent heuristic without an effective-date rule).

dup_count = products["ProductID"].duplicated().sum()
print("Duplicate ProductID rows:", int(dup_count))

if dup_count > 0:
    # Keep the row with the fewest nulls (remove row with less information)
    products = (
        products.assign(_nulls=products.isna().sum(axis=1))
                .sort_values(["ProductID", "_nulls"])
                .drop_duplicates("ProductID", keep="first")
                .drop(columns="_nulls")
                .copy()
    )

print("Product PK unique after cleanup:", products["ProductID"].is_unique)

#Creating publish_product
### Key Assumptions
#Discount is an absolute amount (not %)
#Lead time = business days, ShipDate exclusive
#Unmapped categories labeled 'Unknown' to preserve volume


publish_product = products.copy()

# 1) Replace NULL Color with N/A
color_nulls_before = publish_product["Color"].isna().sum()
publish_product["Color"] = publish_product["Color"].fillna("N/A")
color_nulls_after = publish_product["Color"].isna().sum()

# 2) Enhance ProductCategoryName when NULL using given rules
cat_nulls_before = publish_product["ProductCategoryName"].isna().sum()

sub = (
    publish_product["ProductSubCategoryName"]
    .fillna("")
    .astype(str)
    .str.strip()
)

# Clothing
missing_cat = publish_product["ProductCategoryName"].isna()
publish_product.loc[missing_cat & sub.isin(["Gloves","Shorts","Socks","Tights","Vests"]),
                    "ProductCategoryName"] = "Clothing"

# Accessories
missing_cat = publish_product["ProductCategoryName"].isna()
publish_product.loc[missing_cat & sub.isin(["Locks","Lights","Headsets","Helmets","Pedals","Pumps"]),
                    "ProductCategoryName"] = "Accessories"

# Components
missing_cat = publish_product["ProductCategoryName"].isna()
publish_product.loc[
    missing_cat & (sub.str.contains("Frames", case=False, na=False) | sub.isin(["Wheels","Saddles"])),
    "ProductCategoryName"
] = "Components"

# Bucket remaining NULL categories
#publish_product["ProductCategoryName"] = publish_product["ProductCategoryName"].fillna("Unknown")
cat_nulls_after = publish_product["ProductCategoryName"].isna().sum()

print("Color NULLs before/after:", int(color_nulls_before), "to", int(color_nulls_after))
print("Category NULLs before/after:", int(cat_nulls_before), "to", int(cat_nulls_after))
print("Unknown category count:", int((publish_product["ProductCategoryName"] == "Unknown").sum())
)

#4
#sales order transforms



# 1 Copy inputs (keep raw tables unchanged)
hdr = sales_order_header.copy()
dtl = sales_order_detail.copy()

# 2) Rename Freight to TotalOrderFreight
hdr = hdr.rename(columns={"Freight": "TotalOrderFreight"})

# 3)column checks
required_hdr = ["SalesOrderID", "OrderDate", "ShipDate", "TotalOrderFreight"]
required_dtl = ["SalesOrderID", "SalesOrderDetailID", "ProductID", "OrderQty", "UnitPrice", "UnitPriceDiscount"]

missing_hdr = [c for c in required_hdr if c not in hdr.columns]
missing_dtl = [c for c in required_dtl if c not in dtl.columns]
if missing_hdr:
    raise KeyError(f"Missing header columns: {missing_hdr}")
if missing_dtl:
    raise KeyError(f"Missing detail columns: {missing_dtl}")

# 4) Join detail to header must use a left join bc we want to keep all details
publish_orders = dtl.merge(
    hdr,
    on="SalesOrderID",
    how="left",
    validate="many_to_one",
    indicator=True
)

# 5 Check for unmatched header rows (true orphan lines)
unmatched = int((publish_orders["_merge"] == "left_only").sum())
print("Detail rows with no matching header:", unmatched)
publish_orders = publish_orders.drop(columns="_merge")

# 6) Ensure numeric fields for calculations
for col in ["OrderQty", "UnitPrice", "UnitPriceDiscount"]:
    publish_orders[col] = pd.to_numeric(publish_orders[col], errors="coerce")

# 7) dates must be datetime for lead time, extra check
if not np.issubdtype(publish_orders["OrderDate"].dtype, np.datetime64):
    raise TypeError("OrderDate must be datetime64 (parse before lead time calc).")
if not np.issubdtype(publish_orders["ShipDate"].dtype, np.datetime64):
    raise TypeError("ShipDate must be datetime64 (parse before lead time calc).")

# 8) LeadTimeInBusinessDays (Mon–Fri only and ShipDate exclusive, assumptions)
publish_orders["LeadTimeInBusinessDays"] = pd.Series(pd.NA, index=publish_orders.index, dtype="Int64")
mask = publish_orders["OrderDate"].notna() & publish_orders["ShipDate"].notna()

order = publish_orders.loc[mask, "OrderDate"].values.astype("datetime64[D]")
ship  = publish_orders.loc[mask, "ShipDate"].values.astype("datetime64[D]")

publish_orders.loc[mask, "LeadTimeInBusinessDays"] = np.busday_count(order, ship).astype("int64")

# 9) TotalLineExtendedPrice
publish_orders["TotalLineExtendedPrice"] = (
    publish_orders["OrderQty"] * (publish_orders["UnitPrice"] - publish_orders["UnitPriceDiscount"])
)

# 10)all detail fields + all header fields except SalesOrderID
detail_cols = list(dtl.columns)
header_cols = [c for c in hdr.columns if c != "SalesOrderID"]
publish_orders = publish_orders[detail_cols + header_cols + ["LeadTimeInBusinessDays", "TotalLineExtendedPrice"]].copy()

#quick prints
print("publish_orders shape:", publish_orders.shape)
print("Null lead time rows:", int(publish_orders["LeadTimeInBusinessDays"].isna().sum()))
print("Negative revenue rows:", int((publish_orders["TotalLineExtendedPrice"] < 0).sum()))

publish_orders.head()

# data quality checks:

# 1) Orphan checks
# 1a) Does every order line point to a real product?
orph_prod = ~publish_orders["ProductID"].isin(publish_product["ProductID"])
print(f"Order lines with missing product master: {int(orph_prod.sum())} ({orph_prod.mean()*100:.2f}%)")

# 1b) Does every order line belong to a real order header?
orph_order = ~sales_order_detail["SalesOrderID"].isin(sales_order_header["SalesOrderID"])
print(f"Order lines with missing order header: {int(orph_order.sum())} ({orph_order.mean()*100:.2f}%)")

# 2) Join explosion check: did the detail -> header join multiply rows?
multiplied = len(publish_orders) != len(sales_order_detail)
print(f"Row count detail: {len(sales_order_detail)} | publish_orders: {len(publish_orders)} | multiplied? {multiplied}")

# 3) Lead time checks
# 3a) Did we calculate lead time for every row?
null_lead = int(publish_orders["LeadTimeInBusinessDays"].isna().sum())
print("Null lead time rows:", null_lead)

# 3b) Are any dates impossible (ship before order)?
bad_dates = publish_orders["ShipDate"] < publish_orders["OrderDate"]
print(f"ShipDate before OrderDate rows: {int(bad_dates.sum())} ({bad_dates.mean()*100:.2f}%)")

# 3c) Are there extreme fulfillment delays? (simple outlier threshold)
lt = publish_orders["LeadTimeInBusinessDays"]
lt_outliers = lt.notna() & (lt > 60)
print(f"Lead time > 60 business days: {int(lt_outliers.sum())} ({lt_outliers.mean()*100:.2f}%)")

# 4) Pricing sanity checks (inputs to revenue)
qty_zero = publish_orders["OrderQty"] == 0
print(f"Zero quantity rows: {int(qty_zero.sum())} ({qty_zero.mean()*100:.2f}%)")

unitprice_neg = publish_orders["UnitPrice"] < 0
print(f"Negative UnitPrice rows: {int(unitprice_neg.sum())} ({unitprice_neg.mean()*100:.2f}%)")

discount_neg = publish_orders["UnitPriceDiscount"] < 0
print(f"Negative UnitPriceDiscount rows: {int(discount_neg.sum())} ({discount_neg.mean()*100:.2f}%)")

# 4a) Discount should not exceed UnitPrice
disc_gt_price = publish_orders["UnitPriceDiscount"] > publish_orders["UnitPrice"]
print(f"Discount > UnitPrice rows: {int(disc_gt_price.sum())} ({disc_gt_price.mean()*100:.2f}%)")

# 5) Revenue checks (outputs)
neg_revenue = publish_orders["TotalLineExtendedPrice"] < 0
print(f"Negative revenue rows: {int(neg_revenue.sum())} ({neg_revenue.mean()*100:.2f}%)")

zero_revenue = publish_orders["TotalLineExtendedPrice"] == 0
print(f"Zero revenue rows: {int(zero_revenue.sum())} ({zero_revenue.mean()*100:.2f}%)")

# 5a) Extra check: negative revenue with positive quantity is more suspicious than returns
neg_not_return = neg_revenue & (publish_orders["OrderQty"] > 0)
print(f"Negative revenue with positive quantity (more suspicious): {int(neg_not_return.sum())}")

if int(neg_not_return.sum()) > 0:
    display_cols = [
        "SalesOrderID","SalesOrderDetailID","ProductID",
        "OrderQty","UnitPrice","UnitPriceDiscount","TotalLineExtendedPrice"
    ]
    display(publish_orders.loc[neg_not_return, display_cols].head(10))

# Top color by revenue each year

q1 = publish_orders.merge(
    publish_product[["ProductID", "Color"]],
    on="ProductID",
    how="left",
    validate="many_to_one"
)

# Confirm product attributes joined correctly
missing_color = q1["Color"].isna().sum()
print("Orders with missing Color after join:", int(missing_color))

# Remove any rows without valid dates (none expected)
q1 = q1.dropna(subset=["OrderDate"])

q1["OrderYear"] = q1["OrderDate"].dt.year

# Aggregate net revenue by year times colour
revenue = (
    q1.groupby(["OrderYear", "Color"], as_index=False)["TotalLineExtendedPrice"]
      .sum()
)

#keep colors that tie for the max
max_per_year = (
    revenue.groupby("OrderYear", as_index=False)["TotalLineExtendedPrice"]
           .max()
           .rename(columns={"TotalLineExtendedPrice": "MaxRevenue"})
)

top_color = (
    revenue
    .merge(max_per_year, on="OrderYear")
    .query("TotalLineExtendedPrice == MaxRevenue")
    .drop(columns="MaxRevenue")
    .sort_values(["OrderYear", "Color"])
    .reset_index(drop=True)
)

top_color

"""For each year, I aggregated net revenue by color using TotalLineExtendedPrice, which includes returns and credits to reflect true financial impact. I then selected the highest revenue color per year.
In 2021 the top colour was red, in 2022 and 2023 it was black and in 2024 it was yellow.
To ensure the result is deterministic and reproducible, I added a tie-breaker so that if two colors generated the exact same revenue in a year, the color that comes first alphabetically would be chosen. This avoids random selection that could change depending on sort order or platform. In practice, no exact ties occurred in this dataset, but the rule guarantees consistent results if they did.
"""

#Average LeadTimeInBusinessDays by ProductCategoryName

# Join order lines to the product master so each row gets a category.
# This is a many to one relationship because many order lines map to one product.
q2 = publish_orders.merge(
    publish_product[["ProductID", "ProductCategoryName"]],
    on="ProductID",
    how="left",
    validate="many_to_one"
)

# Check how many order lines did not find a matching category.
# This helps confirm the quality of the product master and join.
missing_before = q2["ProductCategoryName"].isna().sum()
print("Rows with missing category after join (before):", int(missing_before))

missing_after = q2["ProductCategoryName"].isna().sum()
print("Rows with missing category after:", int(missing_after))

# Aggregate to compute the average business-day lead time by category.
# - mean() gives the KPI requested
# - count() shows how many rows contributed to the mean
# - size() shows total line volume per category for context
avg_lead = (
    q2.groupby("ProductCategoryName", as_index=False)
      .agg(
          AvgLeadTimeInBusinessDays=("LeadTimeInBusinessDays", "mean"),
          LinesWithLeadTime=("LeadTimeInBusinessDays", "count"),
          LineCount=("ProductID", "size")
      )
      # Sort so categories with the longest lead times appear first
      .sort_values("AvgLeadTimeInBusinessDays", ascending=False)
      .reset_index(drop=True)
)

# Final result used to answer Analysis Question 2
avg_lead

bad_products = publish_product[publish_product["ProductCategoryName"].isna()]["ProductID"]
publish_orders[publish_orders["ProductID"].isin(bad_products)].shape

"""Average LeadTimeInBusinessDays is very consistent across categories around 5 days. The lowest average is Components and the highest is Unknown, with 37,653 order lines falling into Unknown because ProductCategoryName was missing even after applying the provided enhancement rules.

Summary:
This case study focused on transforming raw product and sales order data into a reliable analytics dataset to support business decision making. The three source tables, Product Master, SalesOrderHeader, and SalesOrderDetail, were loaded, reviewed, and standardized with appropriate data types for dates, prices, and identifiers. Primary and foreign key relationships were validated to ensure order lines correctly referenced existing orders and products, creating a trustworthy foundation for reporting and analysis.

The product master was then cleaned and enriched to improve data quality and usability. Missing values in the Color field were replaced with N/A, and missing ProductCategoryName values were inferred using business rules based on ProductSubCategoryName. This ensured that all products could be grouped into meaningful categories such as Clothing, Accessories, and Components, allowing for consistent aggregation across the business. The sales data was joined and enhanced with two key metrics, LeadTimeInBusinessDays to measure fulfillment speed excluding weekends, and TotalLineExtendedPrice to represent net revenue per order line after discounts.

Using the transformed dataset, two core insights were produced. The analysis identified which product color generated the highest revenue in each year, providing visibility into customer preferences and potential merchandising opportunities. It also evaluated average lead time by product category, highlighting operational differences that can inform inventory planning and service level improvements. Overall, the process delivered a clean, integrated data model that supports both commercial and operational decision making with accurate and actionable metrics.
"""

